Raise an error when sending an email with missing configuration
coopengo/trytond pull request #208
Opened 2023-01-10 07:44 UTC by Melekcoopengo

Fix #PJAZZ_419

2023-01-10 08:59 UTC, jmousset commented on trytond/ir/message.xml
> +            <field name="text">Connection to server failed due to a missing configuration.</field>
La connection avec le serveur de mail  a échoué. Veuillez vérifier votre configuration de serveur d’email.

2023-01-10 10:46 UTC, jmousset requested changes

2023-01-10 10:46 UTC, jmousset commented on trytond/ir/locale/fr.po
> +msgstr "La connexion au serveur de mail a échoué. Veuillez vérifier votre configuration de server d'email."
typo: serveur

et il manque un article devant Connection dnas la version anglaise

2023-01-10 17:40 UTC, jmousset requested changes

2023-01-10 17:40 UTC, jmousset commented on trytond/sendmail.py
> +            raise ValidationError(gettext('ir.msg_missing_configuration'))
ce serait bien de garder une ligne logger.error('fail to connect to %s', uri, exc_info=True) dans le if, pour avoir une trace de l'exception originale dans les logs du serveur.

2023-01-11 08:52 UTC, jmousset commented on trytond/ir/locale/fr.po
> +"The connection to email server failed. Please check your email server configuration."
La traduction est maintenant correct, mais ton message.xml n'est pas à jour.

2023-01-11 09:34 UTC, JCavallo commented on CHANGELOG
> +* Raise an error when sending an email with missing configuration
Pour le coup pour les modifications dans trytond, on ne modifie pas les changelogs

2023-01-11 09:38 UTC, JCavallo commented on CHANGELOG
> +* Raise an error when sending an email with missing configuration
Attention au moment du merge, les modifications sur trytond se font d'une façon particulière @jmousset . Pour le titre, ajourer `[CUSTOM]` à la fain.

2023-01-11 13:39 UTC, JCavallo commented on CHANGELOG
> +* Raise an error when sending an email with missing configuration
yes

2023-01-11 14:48 UTC, merged